<h1>Interface Ingredient</h1>
<div class="formulaire">
    <form action="<?= $requestUrl?>/ingredient" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Ajouter un ingrédient</legend>
            <div>
                <label for="name">name</label>
                <input type="text" name="name" id="name">
            </div>
            <div>
                <label for="type">type</label>
                <select id="type" name="type">
                    <option value="BASE">BASE</option>
                    <option value="PROTEINE">PROTEINE</option>
                    <option value="SUPPLEMENT">SUPPLEMENT</option>
                </select>
            </div>
            <div>
                <label for="prix">prix</label>
                <input type="text" name="prix" id="prix">
            </div>
            <div>
                <input type="file" name="picture" id="picture" />
            </div>
            <div>
                <button>Valider</button>
            </div>
        </fieldset>
    </form>
</div>

<div class="formulaire">
    <form action="<?= $requestUrl?>/dessert" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Ajouter un dessert / boisson</legend>
            <div>
                <label for="name">name</label>
                <input type="text" name="name" id="name">
            </div>
            <div>
                <label for="type">type</label>
                <select id="type" name="type">
                    <option value="boisson">boisson</option>
                    <option value="dessert">dessert</option>
                </select>
            </div>
            <div>
                <label for="prix">prix</label>
                <input type="text" name="prix" id="prix">
            </div>
            <div>
                <input type="file" name="picture" id="picture" />
            </div>
            <div>
                <button>Valider</button>
            </div>
        </fieldset>
    </form>
</div>