<!-- Message de notification -->

<!-- Code HTML à écrire -->

<div class="guycontainer">
                <div class="flex">
                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/salle-du-restaurant.jpg"><p class="hidden">Le Restaurant...</p>

                    </article>

                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/Restaurant-Le-Camion-qui-fume-©Sébastien-Champeaux.jpg"><p class="hidden">...une ambiance...</p>

                    </article>

                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/AVM_79671.jpg" alt="#"><p class="hidden">...quartier...</p>

                    </article>
                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/img_2338.jpg" alt="#"><p class="hidden">...sa terrasse...</p>

                    </article>

                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/Restaurant-Cucina-Byblos_Ambiance_Hotel-Byblos-Saint-Tropez-14-1600x1000.jpg"><p class="hidden">...une cuisine...</p>

                    </article>
                    <article>

                        <img class="imgguy" src="<?= $wwwUrl ?>/images/img/Restaurant-Le-Camion-qui-fume-©Sébastien-Champeaux9.jpg">

                        <p class="hidden">...un concept...</p>    

                    </article>

                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/XVMdfa43516-c065-11e5-b21a-aecb1c98c62d.jpg"><p class="hidden">...un concept...</p> 

                    </article>

                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/vuemezzanine06.jpg"><p class="hidden">...un concept...</p> 

                    </article>


                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/pitaya-bloc-photo-02-restaurant-thailandais.jpg"><p class="hidden">...un concept...</p> 

                    </article>


                    <article>

                    <img class="imgguy" src="<?= $wwwUrl ?>/images/img/tours-1.jpg"><p class="hidden">...un concept...</p>

                    </article>

​

                </div>

​

            </div>