<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <!-- <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css"> -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/index.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/commandestyle.css">

    <!-- <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla"> -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Montserrat+Subrayada&display=swap" rel="stylesheet"> 

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <div>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/pitaya-logo-white_02.png" alt="3WA Restaurant">
        
        <h1 class="Subrayada">Notre Restaurant 3WA !</h1>
        </a>
    </div>
    <!-- Interface utilisateur -->
    <?php if (isset($_SESSION['user']) && $_SESSION['user']['Role'] === 'admin') : ?>
        <nav class="admin-interface">
            <a href="<?= $requestUrl ?>/formule">Ajouter une formule</a>
            <a href="<?= $requestUrl ?>/ingredient">Ajouter des ingrédients</a>
            <a href="<?= $requestUrl ?>/suivreCommande">Suivre les commandes</a>
            <a href="#">Mon panier</a> 
            <?php if (!isset($_SESSION['user'])) : ?>
                <a href="<?= $requestUrl ?>/utilisateur">S'identifier</a>
            <?php else : ?>
                <a id="deconnexion" href="<?= $requestUrl ?>/logout">Déconnexion (<?= $_SESSION['user']['FirstName'] ?>)</a>
            <?php endif ?>
        </nav> 
    <?php else : ?>
        <nav class="user-interface">
            <a href="<?= $requestUrl ?>/menu">Formules Menu</a>
            <a href="<?= $requestUrl ?>/formuleselect">Ma Commande</a>
            <a href="#">Mon panier</a> 
            <?php if (!isset($_SESSION['user'])) : ?>
                <a href="<?= $requestUrl ?>/utilisateur">S'identifier</a>
            <?php else : ?>
                <a id="deconnexion" href="<?= $requestUrl ?>/logout">Déconnexion (<?= $_SESSION['user']['FirstName'] ?>)</a>
            <?php endif ?>
    <?php endif ?>
</nav>
</header>




<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <div>
    <div>
    <p class="Subrayada">Nous trouver</p>
    <p>46 Rue René Clair <br> 75018 Paris</p>
    </div>
    <div>
    <p class="Subrayada">Téléphone : </p>
    <p>01 75 43 42 42</p>
    </div>
    </div>
    <div>
        <p>Ouvert de 11h00 à 14h30&nbsp;</p>
        <p>et de 19h00 à 22h00</p>
    </div>

    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d471444.5037348652!2d167.1500747132476!3d-22.61049269224448!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6c29bbf4d8873a27%3A0x93e47bed00bf08ba!2sL&#39;%C3%8Ele+des+Pins%2C+Nouvelle-Cal%C3%A9donie!5e0!3m2!1sfr!2sfr!4v1564741317942!5m2!1sfr!2sfr" width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>







    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <p  style="text-align: center;">Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</p>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>