<div class="formulaire">
<form action="#" method="post">
<fieldset>
<legend>Se connecter</legend>
<div>
<label for="login">Identifiant</label>
<input type="text" name="login" id="login">
</div>
<div>
<label for="password">Mot de passe</label>
<input type="text" name="password" id="password">
</div>
<div>
<button>Valider</button>
</div>
</fieldset>
</form>
</div>

<div class="formulaire">
<form action="<?= $requestUrl?>/register" method="post">
<fieldset>
<legend>S'enregistrer</legend>
<div>
<label for="firstName">Prénom</label>
<input type="text" name="firstName" id="firstName">
</div>
<div>
<label for="lastName">Nom</label>
<input type="text" name="lastName" id="lastName">
</div>
<div>
<label for="login">Identifiant</label>
<input type="text" name="login" id="login">
</div>
<div>
<label for="motDePasse">Mot de passe</label>
<input type="text" name="motDePasse" id="motDePasse">
</div>
<div>
<label for="mail">Adresse Mail</label>
<input type="text" name="mail" id="mail">
</div>
<div>
<button>Valider</button>
</div>
</fieldset>
</form>
</div>










