<form action="#" method="post">
<fieldset>
<legend>Se connecter</legend>

<!-- <label for="firstName">Prénom</label>
<input type="text" name="firstName" id="firstName">

<label for="lastName">Nom</label>
<input type="text" name="lastName" id="lastName"> -->

<label for="login">Identifiant</label>
<input type="text" name="login" id="login">

<label for="password">Mot de passe</label>
<input type="text" name="password" id="password">

<button>Valider</button>
</fieldset>
</form>

<form action="register" method="post">
<fieldset>
<legend>S'enregistrer</legend>

<label for="firstName">Prénom</label>
<input type="text" name="firstName" id="firstName">

<label for="lastName">Nom</label>
<input type="text" name="lastName" id="lastName">

<label for="login">Identifiant</label>
<input type="text" name="login" id="login">

<label for="password">Mot de passe</label>
<input type="text" name="password" id="password">

<button>Valider</button>
</fieldset>
</form>










