
<h1 class="Subrayada carteTitre">La carte</h1>
<div id="photoCarte">
<img  width=20% src="<?= $wwwUrl ?>/images/meals/cooked-white-rice-thai-jasmine-600w-688370464.jpg" alt="cooked-white">   
<img width=20% src="<?= $wwwUrl ?>/images/meals/spices-herbs-metal-bowls-wooden-600w-127322789.jpg" alt="spices herbs">   
</div>

<div id="menu">
<div>
<h2>Formule Pitaya</h2>
<p>Choisissez votre plat</p>
</div>

<div>
<h2>Formule Medium Pitaya</h2>
<p>Choisissez votre plat <br> + <br> un dessert</p>
</div>

<div>
<h2>Formule Medium Pitaya</h2>
<p>Choisissez votre plat <br> + <br> un dessert <br> + <br> une boisson</p>
</div>
</div>

<div id="flexChoix">
<div class="choix">
<h2>Base</h2>
<p>Riz <hr> Quinoa <hr> Pâtes</p>
</div>

<div class="choix">
<h2>Ingrédients (1 protéine + 4 topping maximum)</h2>
<p>boeuf, poulet, crevettes, tofu</p>
<p>ciboulette thaï, menthe, coriandre, basilic thaï, citron vert, cacahuètes, oignons frits, pousse de soja, salade, algues</p>
</div>

<div class="choix">
<h2>Desserts</h2>
<p>perles de chia au lait de coco & coulis de mangue</p>
<p>double mousse chocolat noir & coco</p>
<p>mousse kalamansi saupoudrée de sablé pur beurre</p>
<p>sorbet mangue</p>
<p>sorbet  noix de coco</p>
<p>sorbet citron basilic</p>
<p>sorbet litchi</p>
</div>
</div>

