
<h1 class="Subrayada carteTitre">La carte</h1>
<div id="photoCarte">
<img  width=20% src="<?= $wwwUrl ?>/images/meals/cooked-white-rice-thai-jasmine-600w-688370464.jpg" alt="cooked-white">   
<img width=20% src="<?= $wwwUrl ?>/images/meals/spices-herbs-metal-bowls-wooden-600w-127322789.jpg" alt="spices herbs">   
</div>

<div id="menu">
<div>
<h2>Formule Pitaya</h2>
<p>Choisissez votre plat</p>
</div>

<div>
<h2>Formule Medium Pitaya</h2>
<p>Choisissez votre plat <br> + <br> un dessert</p>
</div>

<div>
<h2>Formule Medium Pitaya</h2>
<p>Choisissez votre plat <br> + <br> un dessert <br> + <br> une boisson</p>
</div>
</div>

<div id="flexChoix">
<div class="choix red">
<h2>Base</h2>
<p>Riz <hr> Quinoa <hr> Pâtes</p>
</div>

<div class="choix red">
<h2>Ingrédients (1 protéine + 4 topping maximum)</h2>
<p>boeuf, poulet, crevettes, tofu</p>
<p>ciboulette thaï, menthe, coriandre, basilic thaï, citron vert, cacahuètes, oignons frits, pousse de soja, salade, algues</p>
</div>

<div class="choix red">
<h2>Desserts</h2>
<p>perles de chia au lait de coco & coulis de mangue</p>
<p>double mousse chocolat noir & coco</p>
<p>mousse kalamansi saupoudrée de sablé pur beurre</p>
<p>sorbet mangue</p>
<p>sorbet  noix de coco</p>
<p>sorbet citron basilic</p>
<p>sorbet litchi</p>
</div>
</div>

<div id="flexChoix">
<div class="choix green">
<h2>Boissons</h2>
<p>Evian (50cl)</p>
<p>Badoit (50cl)</p>
<p>Coca Cola (33cl)</p>
<p>Coca Cola ZÉro (33cl)</p>
<p>Oasis Tropical (33cl)</p>
<p>Lipton Ice Tea Pêche (33cl)</p>
<p>Fanta Orange (33cl)</p>
</div>

<div class="choix green">
<h2>Boissons exotiques</h2>
<p>Thé Vert Grenade</p>
<p>Thé Vert Pêche</p>
<p>Aloe Vera mangue (50cl)</p>
<p>Vita Coco Eau de coco (33cl)</p>
<p>Litchi</p>
<p>Mangue</p>
</div>

<div class="choix green">
<h2>Bières</h2>
<p>TSINGTAO (33cl)</p>
<p>SINGHA (33cl)</p>
<p>CHANG (32cl)</p>
</div>
</div>














