<div class="addFormule">
    <form action="<?= $requestUrl?>/addformule" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Ajouter une formule</legend>
            <div>
                <label for="name">name</label>
                <input type="text" name="name" id="name">
            </div>
            <div>
                <label for="dessert">dessert</label>
                <input type="text" name="dessert" id="dessert">
            </div>
            <div>
                <label for="boisson">dessert</label>
                <input type="text" name="boisson" id="boisson">
            </div>
            <div>
                <button>Valider</button>
            </div>
        </fieldset>
    </form>
</div>