<h1>Formule au Choix</h1>

<section class="menusimple">

    <h2>Formule Pitaya</h2>

        <h3>Confectionnez votre plat</h3>

            <h4>La base...</h4>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/rice.jpg">Riz</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/quinoa.jpg">Quinoa</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/nouilles.jpg">Pâtes</a>

            <h4>1 protéine...<h/4>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/boeuf.jpg">Boeuf</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/poulet.jpg">Poulet</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/gambas.jpeg">Crevettes</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/toffu.webp">Toffu</a>

            <h4>4 toppings...<h/4>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/ciboulette.jpeg">Ciboulette thaï</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/menthe.jpg">Menthe</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/coriande.jpeg">Coriande</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/basilic.jpeg">Basilic thaï</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/citron.jpeg">Citron vert</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/rice.jpg">Cacahuètes</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/oignon.jpg">Oignon frit</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/poussesdesoja.jpg">Pousse de soja</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/salade.jpg">Salade</a>

                <a href="#"><img class="imgcommande" src="<?= $wwwUrl ?>/images/img/algue.jpg">Algues</a>

    


    <a href=""