<div id="macommande">
       
        <section>
            <h3>Confectionnez votre plat</h3>
                <article>
                    <h4>La base...</h4>
                    <?php foreach($bases as $base) : ?>
                        <div>
                            <figure>
                                <img src="<?= $wwwUrl ?>/images/illustrations/<?= $base['mName']?>"/>
                                <figcaption>
                                    <input id="base-<?= $base['id']?>" name="base" type="radio" value=""/>
                                    <label for="base-<?= $base['id']?>"><?= $base['iName'] ?></label>
                                </figcaption>
                            </figure>
                        </div>
                    <?php endforeach ?>
                </article>
                <article>
                    <h4>1 protéine...</h4>
                    <?php foreach($proteines as $proteine):?>
                        <div>
                            <figure>
                                <img src="<?= $wwwUrl ?>/images/illustrations/<?= $proteine['mName']?>" />
                                <figcaption>
                                    <input id="proteine-<?= $proteine['id'] ?>" name="proteine" type="radio" value=""/>
                                    <label for="proteine-<?= $proteine['id']?>"><?= $proteine['iName'] ?></label>
                                </figcaption>
                            </figure>
                        </div>
                    <?php endforeach ?>
                </article>
                <article>
                    <h4>4 toppings...</h4>
                    <?php foreach($supplements as $supplement):?>
                        
                        `<div>
                            <figure>
                                <img src="<?= $wwwUrl ?>/images/illustrations/<?=$supplement['mName']?>" />
                                <figcaption>
                                    <input id="topping-<?= $supplement['id'] ?>" name="supplement" type="radio" value=""/>
                                    <label for="topping-<?= $supplement['id'] ?>"><?= $supplement['iName'] ?></label>
                                </figcaption>
                            </figure>
                        </div>`
                        <?php endforeach ?>
                </article>
        </section>

</div>
